CREATE TABLE USR01_USER
(
    ID       BIGINT       NOT NULL PRIMARY KEY,
    ENABLED  BIT          NOT NULL,
    NAME     VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    SALT     UNIQUEIDENTIFIER
);

CREATE UNIQUE INDEX USR01_USER_NAME_UINDEX ON USR01_USER (NAME);

CREATE SEQUENCE USR01_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE USR02_AUTHORITIES
(
    ID        BIGINT       NOT NULL PRIMARY KEY,
    AUTHORITY VARCHAR(255) NOT NULL,
    USR01_ID BIGINT,
    FOREIGN KEY (USR01_ID) REFERENCES USR01_USER(ID)
);

CREATE TABLE QUI01_QUIZ
(
    ID      BIGINT NOT NULL PRIMARY KEY,
    NAME    VARCHAR(255),
    USR01_ID BIGINT,
    FOREIGN KEY (USR01_ID) REFERENCES USR01_USER(ID)
);

CREATE TABLE QUI02_QUESTION
(
    ID          BIGINT       NOT NULL PRIMARY KEY,
    ANSWER_TIME BIGINT       NOT NULL,
    IMAGE       VARBINARY(255),
    QUESTION    VARCHAR(255) NOT NULL,
    QUI01_ID     BIGINT,
    FOREIGN KEY (QUI01_ID) REFERENCES QUI01_QUIZ(ID)
);

CREATE TABLE QUI03_ANSWER
(
    ID          BIGINT NOT NULL PRIMARY KEY,
    ANSWER      VARCHAR(255),
    IS_CORRECT  BIT,
    QUI02_ID BIGINT,
    FOREIGN KEY (QUI02_ID) REFERENCES QUI02_QUESTION(ID)
);
